<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10694" started-at="2018-05-09T11:53:51Z" finished-at="2018-05-09T11:54:02Z">
    <groups>
      <group name="dataProviderWithExcel">
        <method signature="DataProviderWithExcel.f([Ljava.lang.String;)[pri:0, instance:com.demo.testNG.DP.DataProviderWithExcel@f6c48ac]" name="f" class="com.demo.testNG.DP.DataProviderWithExcel"/>
      </group> <!-- dataProviderWithExcel -->
      <group name="TestNG">
        <method signature="DataProviderWithExcel.f([Ljava.lang.String;)[pri:0, instance:com.demo.testNG.DP.DataProviderWithExcel@f6c48ac]" name="f" class="com.demo.testNG.DP.DataProviderWithExcel"/>
      </group> <!-- TestNG -->
      <group name="TC008">
        <method signature="DataProviderWithExcel.f([Ljava.lang.String;)[pri:0, instance:com.demo.testNG.DP.DataProviderWithExcel@f6c48ac]" name="f" class="com.demo.testNG.DP.DataProviderWithExcel"/>
      </group> <!-- TC008 -->
      <group name="demo">
        <method signature="DataProviderWithExcel.f([Ljava.lang.String;)[pri:0, instance:com.demo.testNG.DP.DataProviderWithExcel@f6c48ac]" name="f" class="com.demo.testNG.DP.DataProviderWithExcel"/>
      </group> <!-- demo -->
    </groups>
    <test name="Default test" duration-ms="10694" started-at="2018-05-09T11:53:51Z" finished-at="2018-05-09T11:54:02Z">
      <class name="com.demo.testNG.DP.DataProviderWithExcel">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.demo.testNG.DP.DataProviderWithExcel@f6c48ac]" name="beforeMethod" is-config="true" duration-ms="8251" started-at="2018-05-09T17:23:52Z" finished-at="2018-05-09T17:24:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="f([Ljava.lang.String;)[pri:0, instance:com.demo.testNG.DP.DataProviderWithExcel@f6c48ac]" name="f" duration-ms="963" started-at="2018-05-09T17:24:00Z" data-provider="TC001DP" finished-at="2018-05-09T17:24:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@207b8649]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[3]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 3
	at com.demo.testNG.DP.DataProviderWithExcel.f(DataProviderWithExcel.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.demo.testNG.DP.DataProviderWithExcel@f6c48ac]" name="afterMethod" is-config="true" duration-ms="737" started-at="2018-05-09T17:24:01Z" finished-at="2018-05-09T17:24:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.demo.testNG.DP.DataProviderWithExcel -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
