<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="864" started-at="2018-05-25T13:09:15Z" finished-at="2018-05-25T13:09:16Z">
    <groups>
      <group name="dataProviderWithExcel">
        <method signature="DataProviderWithExcel.f(java.util.ArrayList)[pri:0, instance:com.demo.testNG.DP.DataProviderWithExcel@f6c48ac]" name="f" class="com.demo.testNG.DP.DataProviderWithExcel"/>
      </group> <!-- dataProviderWithExcel -->
      <group name="TestNG">
        <method signature="DataProviderWithExcel.f(java.util.ArrayList)[pri:0, instance:com.demo.testNG.DP.DataProviderWithExcel@f6c48ac]" name="f" class="com.demo.testNG.DP.DataProviderWithExcel"/>
      </group> <!-- TestNG -->
      <group name="TC008">
        <method signature="DataProviderWithExcel.f(java.util.ArrayList)[pri:0, instance:com.demo.testNG.DP.DataProviderWithExcel@f6c48ac]" name="f" class="com.demo.testNG.DP.DataProviderWithExcel"/>
      </group> <!-- TC008 -->
      <group name="demo">
        <method signature="DataProviderWithExcel.f(java.util.ArrayList)[pri:0, instance:com.demo.testNG.DP.DataProviderWithExcel@f6c48ac]" name="f" class="com.demo.testNG.DP.DataProviderWithExcel"/>
      </group> <!-- demo -->
    </groups>
    <test name="Default test" duration-ms="864" started-at="2018-05-25T13:09:15Z" finished-at="2018-05-25T13:09:16Z">
      <class name="com.demo.testNG.DP.DataProviderWithExcel">
        <test-method status="FAIL" signature="f(java.util.ArrayList)[pri:0, instance:com.demo.testNG.DP.DataProviderWithExcel@f6c48ac]" name="f" duration-ms="832" started-at="2018-05-25T18:39:15Z" data-provider="TC001DP" finished-at="2018-05-25T18:39:16Z">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
Data provider mismatch
Method: f([Parameter{index=0, type=java.util.ArrayList, declaredAnnotations=[]}])
Arguments: [([Ljava.lang.Object;)[Ljava.lang.Object;@140c9f39]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: f([Parameter{index=0, type=java.util.ArrayList, declaredAnnotations=[]}])
Arguments: [([Ljava.lang.Object;)[Ljava.lang.Object;@140c9f39]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:49)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1187)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- com.demo.testNG.DP.DataProviderWithExcel -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
